config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # get "lists", to: "lists#index"
  # get "lists", to: "lists#show", as: "list"

  # get "lists/new", to: "list#new", as: "new_list"
  # post "lists", to: "lists#create"

  # get "lists/:id/bookmarks/new", to: "bookmarks#new", as: "new_list_bookmark"
  # post "lists/:id/bookmarks/", to: "bookmarks#create", as: "list_bookmarks"

  # delete "bookmarks/:id", to: "bookmarks#destroy", as: "bookmark"

  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: :destroy
end




# A user can see all the lists
# GET "lists"
# A user can see the details of a given list and its name
# GET "lists/42"
# A user can create a new list
# GET "lists/new"
# POST "lists"


# GET "lists/42/bookmarks/new"
# POST "lists/42/bookmarks"
# A user can delete a bookmark from a list. How can we make a delete link again?
# DELETE "bookmarks/25"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end
# A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.
# The comment of a bookmark cannot be shorter than 6 characters.

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end
# A list must have a unique name

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end
# A movie must have a unique title and an overview.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:id])
    @movies = Movie.all
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.new(bookmark_params)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  private
  def bookmark_params
    params.require(:bookmarks).permit(:movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = Movie.all
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    # redirect_to
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmark a Movie for <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.label :movie_id, "Select a movie to bookmark" %>
    <%= f.association :movie, collection: @movies, label_method: :title, value_method: :id, prompt: true, input_html: { class: "form-control" } %>
  </div>
  <div>
    <%= f.submit "Bookmark Movie", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Movie Lists</h1>

<%# index(lists) %>
<%# <%# As a user, I can see all my movie lists %>
<%# display the lists %>
<% @lists.each do |list| %>
  <%= link_to list.name, list_path(list) %>
<% end %>
<%# link/button on individual list --> so a user can see the selected list %>
<%# link/button --> so a user can create a new list %>
<%= link_to 'Create a new list', new_list_path, class: "btn btn-primary" %>

app/views/lists/new.html.erb
<%# index/new(create) %>
<h1>Create a list</h1>
<%# As a user, I can create a movie list %>

<%# form to create new list  %>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<%# show %>

<%# A user can see the details of a given list and its name %>
<%# As a user, I can bookmark a movie inside a movie list %>
<%# As a user, I can destroy a bookmark %>

<%# display movies through the bookmark form (create the bookmark) ---> display movies in list %>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.label :movie_id, "Select a movie to bookmark" %>
    <%= f.association :movie, collection: @movies, label_method: :title, value_method: :id, prompt: true, input_html: { class: "form-control" } %>
  </div>
  <div>
    <%= f.submit "Bookmark Movie", class: "btn btn-primary" %>
  </div>
<% end %>
<%# Display the name of the list
    For each movie in the list:
      Display the movie title
    Provide a link/button to bookmark that movie
    Create a form to bookmark a movie:
    Allow the user to select a movie from the list
    Include a button to submit the form %>

<h6>Movies in this list</h6>
<% @list.bookmarks.each do |bookmark| %>
  <%= link_to bookmark.movie.title, movie_path(bookmark.movie) %>
  <%= link_to 'Remove', list_bookmark_path(@list, bookmark), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>